[server]
enableCORS = true
enableXsrfProtection = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#2563eb"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1a1a1a"