# API Keys
OPENAI_API_KEY = "your-openai-key-here"
LANGCHAIN_API_KEY = "your-langchain-key-here"
LANGCHAIN_PROJECT = "parenting agent2"

# Database credentials
db_username = "postgres.xmyxwdhpdsoykroculgd"  
db_password = "your-db-password-here"
db_host = "aws-0-eu-west-2.pooler.supabase.com"  
db_name = "postgres"
db_port = "6543"

# Admin credentials
ADMIN_PASSWORD = "your-admin-password-here"